### ISSUE TITLE
[BUG] Some mimetypes are missed

### ISSUE THREAD

**Issue by ZorinArch** [4e6anenk0/Rowaita-icon-theme#2]
Hi,

### List with missed mimetypes

*.sh
*.xml
*.drawio
*.ods
*.odt
*.odp
*.deb
*.rpm
*.pkg.tar.zst
*.pkg.tar.xz
*.gzip
*.db
*.sqlite
*.url
*.pub
*.kdbx
*.histfile
*.bak
*.wine
*.msu
*.cab

**P.S** : I will update you with every missed icons i can find

**Comment by 4e6anenk0** [comment]
> Hi,
> 
> ### List with missed mimetypes
> *.sh *.xml *.drawio *.ods *.odt *.odp *.deb *.rpm *.pkg.tar.zst *.pkg.tar.xz *.gzip *.db *.sqlite *.url *.pub *.kdbx *.histfile *.bak *.wine *.msu *.cab
> 
> **P.S** : I will update you with every missed icons i can find

I made a release [1.1.0](https://github.com/4e6anenk0/Rowaita-icon-theme/releases/tag/v1.1.0) with a lot of changes. There are some types out there, but not all. Not for all types I found matches. Some matches can only be added manually. If some types work for you through other icon packages, could you indicate in which package and what kind of icon works? Below is a list of types that should be displayed:

*.sh
*.xml
*.ods
*.odt
*.odp
*.deb
*.rpm
*.gzip
*.sqlite
*.kdbx
*.cab

As I understand it, TypeScript or other similar types, they simply don't exist in matches, and this type must be added manually. I'm adding more icons as someone else can add a match if they want.

Here seems to be a way to add an association to display `*.drawio` files:

https://gist.github.com/giner/0eb272c11085036c4438413f6de0e454

Always open to new feedback, thanks for participating in this repo.
