### ISSUE TITLE
Symbolic icons are missing on KDE

### ISSUE THREAD

**Issue by Vistaus** [4e6anenk0/Rowaita-icon-theme#6]
This is one heck of a beautiful icon theme! But the symbolic icons are missing on KDE on things like buttons (forward, backward, etc.). Would be great if you could fix that. :)

**Comment by 4e6anenk0** [comment]
I thank you for your rating. I'll see what I can do

**Comment by 4e6anenk0** [comment]
But could you attach the screenshots? I want to see where exactly the problem is and what it looks like. Because I have forward and backward buttons on a virtual machine with Manjaro KDE

**Comment by Vistaus** [comment]
Thanks for looking into it! As you can see in the screenshot, the symbolic icons aren't showing on e.g. the Dolphin toolbar:

![Screenshot_20221011_202002](https://user-images.githubusercontent.com/1716229/195169539-b89c13c7-3553-4f9a-94ce-b960e45f633e.png)

**Comment by Vistaus** [comment]
Btw, I forgot to mention, but I'm using openSUSE Tumbleweed. And this is the only icon theme that has this issue - all other icon themes display those icons just fine.

**Comment by 4e6anenk0** [comment]
Very strange behaviour. Maybe it has something to do with the theme. I had a similar problem with flatpak apps, but the solution is in the README. I installed openSUSE Tumbleweed on the virtual machine and the icons were displayed correctly in standard themes. How did you install the icons and in what directory are they located?

**Comment by Vistaus** [comment]
I installed them in /usr/share-icons, just like every other icon theme on my machine.

I'm currently using the Greybird theme with Kvantum. But again: no other icon theme has this issue, so I'm not sure it's theming problem.

**Comment by Vistaus** [comment]
Reinstalled Rowaita and now the icons are working. Not sure what the issue was, but oh well. Thanks again for looking into it! :-)
